import React, { useState } from 'react';
import { Link } from 'react-router-dom';
import { Download, Search, Play, X, Send, ChevronDown, ExternalLink } from 'lucide-react';
import { db } from '../../services/db';
import { GalleryItem, VacancyItem } from '../../types';

const PageHeader: React.FC<{ title: string; description: string }> = ({ title, description }) => (
  <div className="bg-gradient-to-r from-gov-navy to-gov-green text-white p-8 rounded-2xl shadow-lg border border-gov-gold/30">
    <span className="text-xs font-extrabold uppercase tracking-wider text-gov-gold">State Fertilizer Company Limited</span>
    <h2 className="text-3xl font-extrabold mt-2">{title}</h2>
    <p className="text-sm text-slate-200 mt-1 max-w-3xl">{description}</p>
  </div>
);

export const AboutUs: React.FC = () => {
  const [tab, setTab] = useState<'message' | 'team' | 'reports'>('message');
  const minister = db.getMinisterMessage();
  const members = db.getBoardMembers();
  const reports = db.getAnnualReports();
  return <div className="max-w-7xl mx-auto px-4 py-8 space-y-8"><PageHeader title="About Our Organization" description="A public enterprise strengthening Sri Lanka's food security through quality agricultural inputs and accountable service delivery." />
    <div className="flex flex-wrap gap-2 border-b pb-2">{[['message', "Minister's Message"], ['team', 'Board & Executive Team'], ['reports', 'Annual Reports']].map(([key, label]) => <button key={key} onClick={() => setTab(key as typeof tab)} className={`px-4 py-2 rounded-lg text-xs font-bold ${tab === key ? 'bg-gov-navy text-white' : 'bg-white border text-slate-700'}`}>{label}</button>)}</div>
    {tab === 'message' && <section className="bg-white border rounded-2xl p-6 grid md:grid-cols-[180px_1fr] gap-6"><img src={minister.photo} alt={minister.ministerName} className="w-full h-56 object-cover rounded-xl" /><div className="space-y-3"><p className="text-xs font-bold text-gov-goldDark uppercase">{minister.ministry}</p><h3 className="text-2xl font-bold text-gov-navy">{minister.ministerName}</h3><p className="font-semibold text-slate-700">{minister.title}</p><blockquote className="border-l-4 border-gov-gold pl-4 italic text-slate-700">{minister.quote}</blockquote>{minister.messageBody.map(text => <p key={text} className="text-sm text-slate-600 leading-relaxed">{text}</p>)}</div></section>}
    {tab === 'team' && <section className="grid sm:grid-cols-2 lg:grid-cols-4 gap-5">{members.map(member => <article key={member.id} className="bg-white border rounded-2xl overflow-hidden"><img src={member.photo} alt={member.name} className="w-full h-44 object-cover" /><div className="p-4 space-y-2"><span className="text-[10px] uppercase font-bold text-gov-goldDark">{member.type === 'board' ? 'Board of Directors' : 'Senior Management'}</span><h3 className="font-bold text-slate-900">{member.name}</h3><p className="text-xs font-semibold text-gov-navy">{member.designation}</p><p className="text-xs text-slate-600">{member.bio}</p><p className="text-[11px] text-slate-500">{member.qualifications}</p></div></article>)}</section>}
    {tab === 'reports' && <section className="grid md:grid-cols-2 gap-5">{reports.map(report => <article key={report.id} className="bg-white border rounded-2xl p-5 space-y-3"><div className="flex justify-between"><div><span className="text-xs font-bold text-gov-goldDark">FINANCIAL YEAR</span><h3 className="text-xl font-bold text-gov-navy">{report.year}</h3></div><Download className="w-5 h-5 text-gov-green" /></div><p className="text-sm font-semibold">{report.title}</p><p className="text-xs text-slate-600">{report.summary}</p><ul className="text-xs text-slate-600 space-y-1">{report.highlights.map(item => <li key={item}>- {item}</li>)}</ul><a href={report.pdfUrl} download className="inline-flex items-center gap-2 px-3 py-2 bg-gov-navy text-white rounded-lg text-xs font-bold">Download report ({report.fileSize})</a></article>)}</section>}
  </div>;
};

export const VacanciesPage: React.FC = () => {
  const vacancies = db.getVacancies().filter(v => v.status === 'Active');
  const [selected, setSelected] = useState<VacancyItem | null>(null);
  const [submitted, setSubmitted] = useState<string | null>(null);
  const [form, setForm] = useState({ name: '', nic: '', email: '', mobile: '', qualifications: '', experienceYears: 0 });
  const submit = (event: React.FormEvent) => { event.preventDefault(); if (!selected) return; const application = db.submitJobApplication({ vacancyId: selected.id, positionTitle: selected.title, applicantName: form.name, nic: form.nic, email: form.email, mobile: form.mobile, qualifications: form.qualifications, experienceYears: Number(form.experienceYears) }); setSubmitted(application.id); };
  return <div className="max-w-7xl mx-auto px-4 py-8 space-y-8"><PageHeader title="Careers & Vacancies" description="Join the national agricultural supply network. Review official openings and submit your application online." /><div className="grid gap-5">{vacancies.map(vacancy => <article key={vacancy.id} className="bg-white border rounded-2xl p-6 flex flex-col md:flex-row md:items-center justify-between gap-5"><div className="space-y-2"><span className="text-xs font-bold text-gov-goldDark">{vacancy.department}</span><h3 className="text-xl font-bold text-gov-navy">{vacancy.title}</h3><p className="text-sm text-slate-600 max-w-3xl">{vacancy.description}</p><p className="text-xs font-bold text-rose-700">Closing date: {vacancy.closingDate}</p><ul className="text-xs text-slate-500">{vacancy.qualifications.map(item => <li key={item}>- {item}</li>)}</ul></div><div className="flex md:flex-col gap-2 shrink-0"><a href={vacancy.pdfUrl} download className="inline-flex items-center justify-center gap-2 px-3 py-2 border border-gov-navy text-gov-navy rounded-lg text-xs font-bold"><Download className="w-4 h-4" /> Gazette PDF</a><button onClick={() => { setSelected(vacancy); setSubmitted(null); }} className="px-4 py-2 bg-gov-green text-white rounded-lg text-xs font-bold">Apply online</button></div></article>)}</div>
    {selected && <div className="fixed inset-0 z-50 bg-black/60 flex items-center justify-center p-4"><div className="bg-white rounded-2xl max-w-lg w-full p-6 max-h-[90vh] overflow-y-auto"><div className="flex justify-between border-b pb-3 mb-4"><div><h3 className="text-lg font-bold text-gov-navy">Apply: {selected.title}</h3><p className="text-xs text-slate-500">Applications are recorded for HR review.</p></div><button onClick={() => setSelected(null)}><X /></button></div>{submitted ? <div className="p-5 bg-emerald-50 border border-emerald-200 rounded-xl text-sm"><h4 className="font-bold text-emerald-900">Application received</h4><p className="mt-2 text-emerald-800">Reference: <strong>{submitted}</strong>. Keep this reference for correspondence.</p></div> : <form onSubmit={submit} className="space-y-3 text-xs">{[['name', 'Full name'], ['nic', 'NIC / ID number'], ['email', 'Email'], ['mobile', 'Mobile number'], ['qualifications', 'Qualifications']].map(([key, label]) => <label key={key} className="block font-bold text-slate-700">{label}<input required value={form[key as keyof typeof form] as string} type={key === 'email' ? 'email' : 'text'} onChange={e => setForm({ ...form, [key]: e.target.value })} className="w-full mt-1 p-2 border rounded-lg" /></label>)}<label className="block font-bold text-slate-700">Years of experience<input required min="0" type="number" value={form.experienceYears} onChange={e => setForm({ ...form, experienceYears: Number(e.target.value) })} className="w-full mt-1 p-2 border rounded-lg" /></label><button type="submit" className="w-full py-2.5 bg-gov-green text-white font-bold rounded-lg flex items-center justify-center gap-2"><Send className="w-4 h-4" /> Submit application</button></form>}</div></div>}
  </div>;
};

export const GalleryPage: React.FC = () => {
  const items = db.getGalleryItems(); const [filter, setFilter] = useState<'all' | 'image' | 'video'>('all'); const [query, setQuery] = useState(''); const [selected, setSelected] = useState<GalleryItem | null>(null);
  const visible = items.filter(item => (filter === 'all' || item.type === filter) && item.title.toLowerCase().includes(query.toLowerCase()));
  return <div className="max-w-7xl mx-auto px-4 py-8 space-y-8"><PageHeader title="Image & Video Gallery" description="Explore SFCL operations, field work, community programmes, and public events." /><div className="flex flex-col sm:flex-row gap-3 justify-between"><div className="flex gap-2">{[['all', 'All media'], ['image', 'Photos'], ['video', 'Videos']].map(([key, label]) => <button key={key} onClick={() => setFilter(key as typeof filter)} className={`px-3 py-2 rounded-lg text-xs font-bold ${filter === key ? 'bg-gov-navy text-white' : 'bg-white border'}`}>{label}</button>)}</div><div className="relative"><Search className="absolute left-3 top-2.5 w-4 h-4 text-slate-400" /><input placeholder="Search gallery" value={query} onChange={e => setQuery(e.target.value)} className="pl-9 p-2 border rounded-lg text-xs" /></div></div><div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-5">{visible.map(item => <button key={item.id} onClick={() => setSelected(item)} className="text-left bg-white border rounded-2xl overflow-hidden hover:shadow-md"><div className="relative"><img src={item.thumbnail} alt={item.title} className="w-full h-48 object-cover" />{item.type === 'video' && <span className="absolute inset-0 flex items-center justify-center"><span className="bg-gov-navy/90 text-white rounded-full p-3"><Play className="w-5 h-5" /></span></span>}</div><div className="p-4"><span className="text-[10px] uppercase font-bold text-gov-goldDark">{item.category}</span><h3 className="font-bold text-slate-900 mt-1">{item.title}</h3><p className="text-xs text-slate-500 mt-1">{item.date}{item.videoDuration ? ` - ${item.videoDuration}` : ''}</p></div></button>)}</div>{selected && <div className="fixed inset-0 z-50 bg-black/80 flex items-center justify-center p-4" onClick={() => setSelected(null)}><div className="max-w-4xl w-full bg-white rounded-xl overflow-hidden" onClick={e => e.stopPropagation()}><div className="flex justify-between p-3"><h3 className="font-bold text-gov-navy">{selected.title}</h3><button onClick={() => setSelected(null)}><X /></button></div>{selected.type === 'video' ? <iframe title={selected.title} src={selected.url} className="w-full aspect-video" allowFullScreen /> : <img src={selected.url} alt={selected.title} className="w-full max-h-[75vh] object-contain bg-slate-900" />}</div></div>}</div>;
};

export const FAQPage: React.FC = () => {
  const faqs = db.getFAQs(); const [query, setQuery] = useState(''); const [open, setOpen] = useState<string | null>(null); const [language, setLanguage] = useState<'en' | 'si' | 'ta'>('en');
  const visible = faqs.filter(f => `${f.questionEn} ${f.answerEn}`.toLowerCase().includes(query.toLowerCase()));
  return <div className="max-w-5xl mx-auto px-4 py-8 space-y-8"><PageHeader title="Frequently Asked Questions" description="Find clear answers about products, bungalow reservations, procurement, and laboratory services." /><div className="flex flex-col sm:flex-row gap-3"><div className="relative flex-1"><Search className="absolute left-3 top-2.5 w-4 h-4 text-slate-400" /><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search questions" className="w-full pl-9 p-2.5 border rounded-lg text-sm" /></div><select value={language} onChange={e => setLanguage(e.target.value as typeof language)} className="p-2.5 border rounded-lg text-sm"><option value="en">English</option><option value="si">Sinhala</option><option value="ta">Tamil</option></select></div><div className="space-y-3">{visible.map(item => { const question = language === 'si' ? item.questionSi : language === 'ta' ? item.questionTa : item.questionEn; const answer = language === 'si' ? item.answerSi : language === 'ta' ? item.answerTa : item.answerEn; return <div key={item.id} className="bg-white border rounded-xl"><button onClick={() => setOpen(open === item.id ? null : item.id)} className="w-full p-4 flex justify-between text-left font-bold text-gov-navy"><span>{question}</span><ChevronDown className={`w-4 h-4 transition ${open === item.id ? 'rotate-180' : ''}`} /></button>{open === item.id && <p className="px-4 pb-4 text-sm text-slate-600 leading-relaxed">{answer}</p>}</div>; })}</div><Link to="/contact" className="inline-flex px-4 py-2 bg-gov-green text-white rounded-lg text-xs font-bold">Still need help? Contact SFCL</Link></div>;
};

export const SiteMapPage: React.FC = () => { const groups = [{ title: 'Main services', links: [['Home', '/'], ['Products catalogue', '/products'], ['Price list', '/fertilizer-prices'], ['Bungalow reservations', '/circuit-bungalows'], ['Procurement & tenders', '/procurement']] }, { title: 'Corporate information', links: [['About SFCL', '/about'], ['Testing laboratory', '/testing-lab'], ['Careers & vacancies', '/vacancies'], ['Gallery', '/gallery'], ['FAQs', '/faq'], ['Contact us', '/contact'], ['RTI', '/rti']] }, { title: 'Customer utilities', links: [['Shopping cart', '/cart'], ['Order tracking', '/order-tracking'], ['Site search', '/search']] }, { title: 'Administration', links: [['Admin portal', '/admin'], ['Booking management', '/admin/bookings'], ['Media and vacancies', '/admin/gallery'], ['Reports and audit', '/admin/reports']] }]; return <div className="max-w-6xl mx-auto px-4 py-8 space-y-8"><PageHeader title="SFCL Website Sitemap" description="Navigate the public services, corporate information, customer utilities, and administration portal." /><div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-5">{groups.map(group => <section key={group.title} className="bg-white border rounded-2xl p-5"><h3 className="font-bold text-gov-green uppercase text-xs border-b pb-3">{group.title}</h3><ul className="mt-3 space-y-2 text-sm">{group.links.map(([label, path]) => <li key={path}><Link to={path} className="text-slate-700 hover:text-gov-green flex items-center gap-2"><ExternalLink className="w-3 h-3" />{label}</Link></li>)}</ul></section>)}</div></div>; };
